/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportAcademy;

import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AsadUllah
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        addRecordButton = new javax.swing.JButton();
        displayRecordButton = new javax.swing.JButton();
        searchRecordButton = new javax.swing.JButton();
        sortAndDisplayButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        sportjTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        SortAndDisplayPanel = new javax.swing.JPanel();
        ascendingOrderRadioButton = new javax.swing.JRadioButton();
        hourlyRateRadioButton = new javax.swing.JRadioButton();
        coachPerformanceRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        SearchRecordPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        coachIdRadio = new javax.swing.JRadioButton();
        sportIdRadio = new javax.swing.JRadioButton();
        studentIdRadio = new javax.swing.JRadioButton();
        coachRatingsRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchSpecificRecordjTable = new javax.swing.JTable();
        searchIdSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        serachResultArea = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        addRecordPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        addCoachNameField = new javax.swing.JTextField();
        addAddressField = new javax.swing.JTextField();
        addDateJoinedSpinner = new javax.swing.JSpinner();
        addHourlyRateSpinner = new javax.swing.JSpinner();
        addSportCenterSpinner = new javax.swing.JSpinner();
        addSportCodeSpinner = new javax.swing.JSpinner();
        addCoachIdSpinner = new javax.swing.JSpinner();
        addPhoneSpinner = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addSportName = new javax.swing.JTextField();
        addSportSchedule = new javax.swing.JTextField();
        addSportCode = new javax.swing.JSpinner();
        addSportFees = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        MODIFYPANEL = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        coachModifyButton = new javax.swing.JButton();
        modifyIdTextField = new javax.swing.JTextField();
        modifyDateJoinedTextField = new javax.swing.JTextField();
        modifyPhoneTextField = new javax.swing.JTextField();
        modifyNameTextField = new javax.swing.JTextField();
        modifyHourlyRateTextField = new javax.swing.JTextField();
        modifyCoachSportCenterCodeTextField = new javax.swing.JTextField();
        modifyAddressTextField = new javax.swing.JTextField();
        modifyRatingsCode = new javax.swing.JTextField();
        modifyCodeSportCodeTextField = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        modifySportSportCodeTextField = new javax.swing.JTextField();
        modifySportSportNameTextField = new javax.swing.JTextField();
        modifySportSportScheduleTextField = new javax.swing.JTextField();
        modifySportSportFeesTextField = new javax.swing.JTextField();
        modifySportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addRecordButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addRecordButton.setText("Add Record");
        addRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 255, 157, -1));

        displayRecordButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        displayRecordButton.setText("DisplaylRecord");
        displayRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayRecordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(displayRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 157, -1));

        searchRecordButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchRecordButton.setText("Search Record");
        searchRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecordButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchRecordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 157, -1));

        sortAndDisplayButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sortAndDisplayButton.setText("Sort And Display");
        sortAndDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortAndDisplayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sortAndDisplayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 157, -1));

        modifyButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyButton.setText("Modify");
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(modifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 157, -1));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 157, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 631));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DefaultTableModel coachTableModel = new DefaultTableModel(new Object[][] {},
            new String[]{"CoachID", "Name", "Date Joined", "Date Terminated","Hourly Rate", "Phone", "Address", "Sport Center Code", "Sport Code", "Ratings"});
        populateCoachTable(coachTableModel);
        jTable3.setModel(coachTableModel);
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 928, 282));

        jTabbedPane1.addTab("COACH", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DefaultTableModel sportTableModel = new DefaultTableModel(new Object[][] {},
            new String[]{"Code", "Name", "Fees", "Schedule"});
        populateSportTable(sportTableModel);
        sportjTable.setModel(sportTableModel);
        jScrollPane4.setViewportView(sportjTable);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 576, 218));

        jTabbedPane1.addTab("SPORT", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DefaultTableModel stdTableModel = new DefaultTableModel(new Object[][] {},
            new String[]{"StudentID", "Sport Center Code","CoachID", "Sport Code", "Age", "Address",});
        //populateStudentTable(stdTableModel);
        jTable4.setModel(coachTableModel);
        jScrollPane6.setViewportView(jTable4);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 928, 282));

        jTabbedPane1.addTab("REGISTERD STUDENTS", jPanel4);

        jLayeredPane1.add(jTabbedPane1, "card2");

        SortAndDisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(ascendingOrderRadioButton);
        ascendingOrderRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ascendingOrderRadioButton.setText("COACHES IN ASCENDING ORDER BY NAME");
        SortAndDisplayPanel.add(ascendingOrderRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        buttonGroup1.add(hourlyRateRadioButton);
        hourlyRateRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hourlyRateRadioButton.setText("HOURLY PAY RATE IN ASCENDING ORDER");
        SortAndDisplayPanel.add(hourlyRateRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 112, -1, -1));

        buttonGroup1.add(coachPerformanceRadioButton);
        coachPerformanceRadioButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coachPerformanceRadioButton.setText("COACHES BY OVERALL PERFOMANCE IN ASCENDING ORDER");
        SortAndDisplayPanel.add(coachPerformanceRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 173, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SORT AND DISPLAY");
        SortAndDisplayPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 25, -1, -1));

        jTable5.setAutoCreateRowSorter(true);
        jTable5.setModel(coachTableModel);
        jScrollPane5.setViewportView(jTable5);

        SortAndDisplayPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 229, 928, 282));

        jLayeredPane1.add(SortAndDisplayPanel, "card3");

        SearchRecordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setText("SEARCH SPECIFIC RECORD");
        SearchRecordPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 27, -1, -1));

        buttonGroup2.add(coachIdRadio);
        coachIdRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coachIdRadio.setText("COACH BY COACH ID ");
        SearchRecordPanel.add(coachIdRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 240, -1, -1));

        buttonGroup2.add(sportIdRadio);
        sportIdRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sportIdRadio.setText("SPORT BY SPORT ID");
        sportIdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportIdRadioActionPerformed(evt);
            }
        });
        SearchRecordPanel.add(sportIdRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 344, -1, -1));

        buttonGroup2.add(studentIdRadio);
        studentIdRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentIdRadio.setText("STUDENT BY STUDENT ID");
        studentIdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdRadioActionPerformed(evt);
            }
        });
        SearchRecordPanel.add(studentIdRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 396, -1, -1));

        buttonGroup2.add(coachRatingsRadio);
        coachRatingsRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coachRatingsRadio.setText("COACH BY OVERALL PERFORMANCE (RATINGS)");
        SearchRecordPanel.add(coachRatingsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 293, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SEARCH");
        SearchRecordPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 157, -1, -1));

        searchSpecificRecordjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(searchSpecificRecordjTable);

        SearchRecordPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 135, -1, 100));

        searchIdSpinner.setModel(new javax.swing.SpinnerNumberModel());
        SearchRecordPanel.add(searchIdSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, 30));

        serachResultArea.setColumns(20);
        serachResultArea.setRows(5);
        jScrollPane2.setViewportView(serachResultArea);

        SearchRecordPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 450, 280));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        SearchRecordPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, 30));

        jLayeredPane1.add(SearchRecordPanel, "card4");

        addRecordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 204));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 32, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NAME");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("HOURLY RATE");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DATE JOINED");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PHONE");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ADDRESS");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("SPORT CENTER CODE");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("SPORT CODE");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("ADD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 471, -1, -1));

        addCoachNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(addCoachNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 167, 31));

        addAddressField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddressFieldActionPerformed(evt);
            }
        });
        jPanel5.add(addAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 167, 31));

        addDateJoinedSpinner.setModel(new javax.swing.SpinnerDateModel());
        jPanel5.add(addDateJoinedSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 170, 30));

        addHourlyRateSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addHourlyRateSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 30));

        addSportCenterSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addSportCenterSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, 30));

        addSportCodeSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addSportCodeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 170, 30));

        addCoachIdSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addCoachIdSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 30));

        addPhoneSpinner.setModel(new javax.swing.SpinnerNumberModel(10000000000L, 10000000000L, null, 1L));
        jPanel5.add(addPhoneSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("New  Coach Record");
        jPanel5.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 330, 40));

        jTabbedPane2.addTab("COACH", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SPORT CODE");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 81, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SPORT NAME");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("SPORT FEES");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 295, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("SPORT SCHEDULE");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 411, -1, -1));

        addSportName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel6.add(addSportName, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 180, 141, 34));

        addSportSchedule.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel6.add(addSportSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 394, 141, 34));

        addSportCode.setModel(new javax.swing.SpinnerNumberModel());
        jPanel6.add(addSportCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 140, 30));

        addSportFees.setModel(new javax.swing.SpinnerNumberModel());
        jPanel6.add(addSportFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 140, 30));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 130, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("New Sport Record");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 370, 40));

        jTabbedPane2.addTab("SPORT", jPanel6);

        addRecordPanel.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel());
        addRecordPanel.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 30));

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel());
        addRecordPanel.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, 30));

        jLayeredPane1.add(addRecordPanel, "card5");

        MODIFYPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setBackground(new java.awt.Color(0, 0, 204));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 37, 32, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("NAME");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 86, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("HOURLY RATE");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 184, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("DATE JOINED");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 135, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("PHONE");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 233, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("ADDRESS");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 282, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("SPORT CENTER CODE");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 331, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("SPORT CODE");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 380, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("RATINGS (1 - 5) ");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 429, -1, -1));

        coachModifyButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coachModifyButton.setText("MODIFY");
        coachModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachModifyButtonActionPerformed(evt);
            }
        });
        jPanel7.add(coachModifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 471, -1, -1));

        modifyIdTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.add(modifyIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 30, 167, 31));

        modifyDateJoinedTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.add(modifyDateJoinedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 128, 167, 31));

        modifyPhoneTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyPhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyPhoneTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(modifyPhoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 226, 167, 31));

        modifyNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.add(modifyNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 79, 167, 31));

        modifyHourlyRateTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyHourlyRateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyHourlyRateTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(modifyHourlyRateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 177, 167, 31));

        modifyCoachSportCenterCodeTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyCoachSportCenterCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCoachSportCenterCodeTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(modifyCoachSportCenterCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 324, 167, 31));

        modifyAddressTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyAddressTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(modifyAddressTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 275, 167, 31));

        modifyRatingsCode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyRatingsCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyRatingsCodeActionPerformed(evt);
            }
        });
        jPanel7.add(modifyRatingsCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 422, 167, 31));

        modifyCodeSportCodeTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifyCodeSportCodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCodeSportCodeTextFieldActionPerformed(evt);
            }
        });
        jPanel7.add(modifyCodeSportCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 373, 167, 31));

        jTabbedPane3.addTab("COACH", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("SPORT CODE");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 81, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("SPORT NAME");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("SPORT FEES");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 295, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("SPORT SCHEDULE");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 411, -1, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("MODIFY");
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 528, 114, -1));

        modifySportSportCodeTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(modifySportSportCodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 73, 141, 34));

        modifySportSportNameTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(modifySportSportNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 180, 141, 34));

        modifySportSportScheduleTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(modifySportSportScheduleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 394, 141, 34));

        modifySportSportFeesTextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(modifySportSportFeesTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 287, 141, 34));

        modifySportButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modifySportButton.setText("MODIFY");
        modifySportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifySportButtonActionPerformed(evt);
            }
        });
        jPanel8.add(modifySportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 471, -1, -1));

        jTabbedPane3.addTab("SPORT", jPanel8);

        MODIFYPANEL.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        jLayeredPane1.add(MODIFYPANEL, "card6");

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void displayRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayRecordButtonActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(jTabbedPane1);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_displayRecordButtonActionPerformed

    private void sortAndDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortAndDisplayButtonActionPerformed
         jLayeredPane1.removeAll();
        jLayeredPane1.add(SortAndDisplayPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_sortAndDisplayButtonActionPerformed

    private void searchRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecordButtonActionPerformed
         jLayeredPane1.removeAll();
        jLayeredPane1.add(SearchRecordPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_searchRecordButtonActionPerformed

    private void addRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordButtonActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(addRecordPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_addRecordButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(MODIFYPANEL);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAddressFieldActionPerformed

    private void modifyPhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyPhoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyPhoneTextFieldActionPerformed

    private void modifyHourlyRateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyHourlyRateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyHourlyRateTextFieldActionPerformed

    private void modifyCoachSportCenterCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCoachSportCenterCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyCoachSportCenterCodeTextFieldActionPerformed

    private void modifyAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyAddressTextFieldActionPerformed

    private void modifyRatingsCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyRatingsCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyRatingsCodeActionPerformed

    private void modifyCodeSportCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCodeSportCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifyCodeSportCodeTextFieldActionPerformed

    private void coachModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachModifyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachModifyButtonActionPerformed

    private void sportIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportIdRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportIdRadioActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        GregorianCalendar joinedDate = (GregorianCalendar) GregorianCalendar.getInstance();
        joinedDate.setTime((Date) addDateJoinedSpinner.getValue());
        Coach newCoach = new Coach(
                addCoachNameField.getText(),
                joinedDate,
                (int)addHourlyRateSpinner.getValue(),//Hourly rate
                (long)addPhoneSpinner.getValue(),//Phone
                addAddressField.getText(),//address
                (int) addSportCenterSpinner.getValue(),//sportcentercode
                (int) addSportCodeSpinner.getValue()//sportcenter
        );
        if(newCoach.saveToDisk()){//If successfull
            JOptionPane.showMessageDialog(AdminFrame.this, "Coach Record added successfully");
        }
        else{
            JOptionPane.showMessageDialog(AdminFrame.this, "Couldn't save record...");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void studentIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdRadioActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(coachIdRadio.isSelected()){
            Coach foundCoach = Coach.findInDisk((int) searchIdSpinner.getValue());
            if(foundCoach!=null){
                this.serachResultArea.setText(Coach.toJson(foundCoach));
            }
            else{
                JOptionPane.showMessageDialog(null, "Record not found...");
            }
        }
        else if(coachRatingsRadio.isSelected()){
            ArrayList<Coach> foundCoachList = Coach.findInDiskByRatings((int) searchIdSpinner.getValue());
            if(foundCoachList.size()>0){
                for(int j=0; j<foundCoachList.size(); j++){
                    this.serachResultArea.append(Coach.toJson(foundCoachList.get(j))+"\n");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Records not found...");
            }
        }
        else if(sportIdRadio.isSelected()){
            Sport foundSport = Sport.findInDisk((int)searchIdSpinner.getValue());
            if(foundSport!=null){
                this.serachResultArea.setText(Sport.toJson(foundSport));
            }
            else{
                JOptionPane.showMessageDialog(null, "Record not found...");             
            }
        }
        else if(studentIdRadio.isSelected()){
            Student foundStd = Student.findInDisk((int) searchIdSpinner.getValue());
            if(foundStd!=null){
                this.serachResultArea.setText(Student.toJson(foundStd));
            }
            else{
                JOptionPane.showMessageDialog(null, "Record not found...");             
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void modifySportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifySportButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modifySportButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Sport newSport = new Sport(
                (int) addSportCode.getValue(),//code
                addSportName.getText(),//name
                (int) addSportFees.getValue(),//fees
                addSportSchedule.getText()//schedule
        );
        if(newSport.saveToDisk()){
            JOptionPane.showMessageDialog(AdminFrame.this, "Record saved successflly...");
        }
        else{
            JOptionPane.showMessageDialog(AdminFrame.this, "Couldn't save record....");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
    private void populateSportTable(DefaultTableModel sportTableModel){
        ArrayList<Sport> sportList = Sport.getAllSports();
        if(sportTableModel.getRowCount()>0){
            for(int i=0; i<sportTableModel.getRowCount(); i++){
                sportTableModel.removeRow(i);
            }
        }
        for(int i=0; i<sportList.size(); i++){
            Object[] row = new Object[4];
            row[0] = sportList.get(i).getCode();
            row[1] = sportList.get(i).getName();
            row[2] = sportList.get(i).getFees();
            row[3] = sportList.get(i).getSchedule();
            sportTableModel.addRow(row);
        }
    }
    private void populateCoachTable(DefaultTableModel coachTableModel){
        ArrayList<Coach> coachList = Coach.getAllCoaches();
        if(coachTableModel.getRowCount()>0){
            for(int i=0; i<coachTableModel.getRowCount(); i++){
                coachTableModel.removeRow(i);
            }
        }
        for(int i=0; i<coachList.size(); i++){
            Object[] row = new Object[10];
            row[0] = coachList.get(i).getId();
            row[1] = coachList.get(i).getName();
            row[2] = coachList.get(i).getDateJoined();
            row[3] = coachList.get(i).getDateTerminated();
            row[4] = coachList.get(i).getHourlyRate();
            row[5] = coachList.get(i).getPhone();
            row[6] = coachList.get(i).getAddress();
            row[7] = coachList.get(i).getSportCenterCode();
            row[8] = coachList.get(i).getSportCode();
            row[9] = coachList.get(i).getRatings();
            coachTableModel.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MODIFYPANEL;
    private javax.swing.JPanel SearchRecordPanel;
    private javax.swing.JPanel SortAndDisplayPanel;
    private javax.swing.JTextField addAddressField;
    private javax.swing.JSpinner addCoachIdSpinner;
    private javax.swing.JTextField addCoachNameField;
    private javax.swing.JSpinner addDateJoinedSpinner;
    private javax.swing.JSpinner addHourlyRateSpinner;
    private javax.swing.JSpinner addPhoneSpinner;
    private javax.swing.JButton addRecordButton;
    private javax.swing.JPanel addRecordPanel;
    private javax.swing.JSpinner addSportCenterSpinner;
    private javax.swing.JSpinner addSportCode;
    private javax.swing.JSpinner addSportCodeSpinner;
    private javax.swing.JSpinner addSportFees;
    private javax.swing.JTextField addSportName;
    private javax.swing.JTextField addSportSchedule;
    private javax.swing.JRadioButton ascendingOrderRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton coachIdRadio;
    private javax.swing.JButton coachModifyButton;
    private javax.swing.JRadioButton coachPerformanceRadioButton;
    private javax.swing.JRadioButton coachRatingsRadio;
    private javax.swing.JButton displayRecordButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton hourlyRateRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField modifyAddressTextField;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField modifyCoachSportCenterCodeTextField;
    private javax.swing.JTextField modifyCodeSportCodeTextField;
    private javax.swing.JTextField modifyDateJoinedTextField;
    private javax.swing.JTextField modifyHourlyRateTextField;
    private javax.swing.JTextField modifyIdTextField;
    private javax.swing.JTextField modifyNameTextField;
    private javax.swing.JTextField modifyPhoneTextField;
    private javax.swing.JTextField modifyRatingsCode;
    private javax.swing.JButton modifySportButton;
    private javax.swing.JTextField modifySportSportCodeTextField;
    private javax.swing.JTextField modifySportSportFeesTextField;
    private javax.swing.JTextField modifySportSportNameTextField;
    private javax.swing.JTextField modifySportSportScheduleTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JSpinner searchIdSpinner;
    private javax.swing.JButton searchRecordButton;
    private javax.swing.JTable searchSpecificRecordjTable;
    private javax.swing.JTextArea serachResultArea;
    private javax.swing.JButton sortAndDisplayButton;
    private javax.swing.JRadioButton sportIdRadio;
    private javax.swing.JTable sportjTable;
    private javax.swing.JRadioButton studentIdRadio;
    // End of variables declaration//GEN-END:variables
}
