/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportAcademy;

import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AsadUllah
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        SortAndDisplayPanel = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        SearchRecordPanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        coachIdRadio = new javax.swing.JRadioButton();
        sportIdRadio = new javax.swing.JRadioButton();
        studentIdRadio = new javax.swing.JRadioButton();
        coachRatingsRadio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchIdSpinner = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        serachResultArea = new javax.swing.JTextArea();
        searchButton = new javax.swing.JButton();
        addRecordPanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        addCoachNameField = new javax.swing.JTextField();
        addAddressField = new javax.swing.JTextField();
        addDateJoinedSpinner = new javax.swing.JSpinner();
        addHourlyRateSpinner = new javax.swing.JSpinner();
        addSportCenterSpinner = new javax.swing.JSpinner();
        addSportCodeSpinner = new javax.swing.JSpinner();
        addCoachIdSpinner = new javax.swing.JSpinner();
        addPhoneSpinner = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        MODIFYPANEL = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Add Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 255, 157, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("DisplaylRecord");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 157, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Search Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 157, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Sort And Display");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 157, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Modify");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 157, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 157, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 631));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DefaultTableModel coachTableModel = new DefaultTableModel(new Object[][] {},
            new String[]{"CoachID", "Name", "Date Joined", "Date Terminated","Hourly Rate", "Phone", "Address", "Sport Center Code", "Sport Code", "Ratings"});
        populateCoachTable(coachTableModel);
        jTable3.setModel(coachTableModel);
        jScrollPane3.setViewportView(jTable3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, 928, 282));

        jTabbedPane1.addTab("COACH", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CODE", "NAME", "FEES", "SCHEDULE"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 576, 218));

        jTabbedPane1.addTab("SPORT", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("jButton9");
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 98, -1, -1));

        jTabbedPane1.addTab("REGISTERD STUDENTS", jPanel4);

        jLayeredPane1.add(jTabbedPane1, "card2");

        SortAndDisplayPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton5.setText("COACHES IN ASCENDING ORDER BY NAME");
        SortAndDisplayPanel.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton6.setText("HOURLY PAY RATE IN ASCENDING ORDER");
        SortAndDisplayPanel.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 112, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton7.setText("COACHES BY OVERALL PERFOMANCE IN ASCENDING ORDER");
        SortAndDisplayPanel.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 173, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SORT AND DISPLAY");
        SortAndDisplayPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 25, -1, -1));

        jTable5.setAutoCreateRowSorter(true);
        jTable5.setModel(coachTableModel);
        jScrollPane5.setViewportView(jTable5);

        SortAndDisplayPanel.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 229, 928, 282));

        jLayeredPane1.add(SortAndDisplayPanel, "card3");

        SearchRecordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setText("SEARCH SPECIFIC RECORD");
        SearchRecordPanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 27, -1, -1));

        buttonGroup2.add(coachIdRadio);
        coachIdRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coachIdRadio.setText("COACH BY COACH ID ");
        SearchRecordPanel.add(coachIdRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 240, -1, -1));

        buttonGroup2.add(sportIdRadio);
        sportIdRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sportIdRadio.setText("SPORT BY SPORT ID");
        sportIdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportIdRadioActionPerformed(evt);
            }
        });
        SearchRecordPanel.add(sportIdRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 344, -1, -1));

        buttonGroup2.add(studentIdRadio);
        studentIdRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentIdRadio.setText("STUDENT BY STUDENT ID");
        studentIdRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIdRadioActionPerformed(evt);
            }
        });
        SearchRecordPanel.add(studentIdRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 396, -1, -1));

        buttonGroup2.add(coachRatingsRadio);
        coachRatingsRadio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        coachRatingsRadio.setText("COACH BY OVERALL PERFORMANCE (RATINGS)");
        SearchRecordPanel.add(coachRatingsRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 293, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("SEARCH");
        SearchRecordPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 157, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        SearchRecordPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 135, -1, 100));

        searchIdSpinner.setModel(new javax.swing.SpinnerNumberModel());
        SearchRecordPanel.add(searchIdSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, 30));

        serachResultArea.setColumns(20);
        serachResultArea.setRows(5);
        jScrollPane2.setViewportView(serachResultArea);

        SearchRecordPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 450, 280));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        SearchRecordPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 100, 30));

        jLayeredPane1.add(SearchRecordPanel, "card4");

        addRecordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 204));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 37, 32, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("NAME");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 86, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("HOURLY RATE");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 184, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("DATE JOINED");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 135, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("PHONE");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 233, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("ADDRESS");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 282, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("SPORT CENTER CODE");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 331, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("SPORT CODE");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 380, -1, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("ADD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 471, -1, -1));

        addCoachNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(addCoachNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 167, 31));

        addAddressField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAddressFieldActionPerformed(evt);
            }
        });
        jPanel5.add(addAddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 167, 31));

        addDateJoinedSpinner.setModel(new javax.swing.SpinnerDateModel());
        jPanel5.add(addDateJoinedSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 170, 30));

        addHourlyRateSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addHourlyRateSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 30));

        addSportCenterSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addSportCenterSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 170, 30));

        addSportCodeSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addSportCodeSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 170, 30));

        addCoachIdSpinner.setModel(new javax.swing.SpinnerNumberModel());
        jPanel5.add(addCoachIdSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 170, 30));

        addPhoneSpinner.setModel(new javax.swing.SpinnerNumberModel(10000000000L, 10000000000L, null, 1L));
        jPanel5.add(addPhoneSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 170, 30));

        jTabbedPane2.addTab("COACH", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("SPORT CODE");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 81, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("SPORT NAME");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("SPORT FEES");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 295, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("SPORT SCHEDULE");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 411, -1, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("ADD");
        jPanel6.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 528, 102, -1));

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel6.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 73, 141, 34));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel6.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 180, 141, 34));

        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel6.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 394, 141, 34));

        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel6.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 287, 141, 34));

        jTabbedPane2.addTab("SPORT", jPanel6);

        addRecordPanel.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel());
        addRecordPanel.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 30));

        jSpinner5.setModel(new javax.swing.SpinnerNumberModel());
        addRecordPanel.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 200, 30));

        jLayeredPane1.add(addRecordPanel, "card5");

        MODIFYPANEL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setBackground(new java.awt.Color(0, 0, 204));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 37, 32, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("NAME");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 86, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("HOURLY RATE");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 184, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("DATE JOINED");
        jPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 135, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("PHONE");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 233, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("ADDRESS");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 282, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("SPORT CENTER CODE");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 331, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("SPORT CODE");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 380, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("RATINGS (1 - 5) ");
        jPanel7.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 429, -1, -1));

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("MODIFY");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 471, -1, -1));

        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 30, 167, 31));

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 128, 167, 31));

        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 226, 167, 31));

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 79, 167, 31));

        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 177, 167, 31));

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField19ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 324, 167, 31));

        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 275, 167, 31));

        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField21ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 422, 167, 31));

        jTextField22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 373, 167, 31));

        jTabbedPane3.addTab("COACH", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("SPORT CODE");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 81, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("SPORT NAME");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, -1, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("SPORT FEES");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 295, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("SPORT SCHEDULE");
        jPanel8.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 411, -1, -1));

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton12.setText("MODIFY");
        jPanel8.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 528, 114, -1));

        jTextField23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 73, 141, 34));

        jTextField24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 180, 141, 34));

        jTextField25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 394, 141, 34));

        jTextField26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel8.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 287, 141, 34));

        jTabbedPane3.addTab("SPORT", jPanel8);

        MODIFYPANEL.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLayeredPane1.add(MODIFYPANEL, "card6");

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(jTabbedPane1);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         jLayeredPane1.removeAll();
        jLayeredPane1.add(SortAndDisplayPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jLayeredPane1.removeAll();
        jLayeredPane1.add(SearchRecordPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(addRecordPanel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(MODIFYPANEL);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAddressFieldActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField19ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField21ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void sportIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportIdRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sportIdRadioActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        GregorianCalendar joinedDate = (GregorianCalendar) GregorianCalendar.getInstance();
        joinedDate.setTime((Date) addDateJoinedSpinner.getValue());
        Coach newCoach = new Coach(
                addCoachNameField.getText(),
                joinedDate,
                (int)addHourlyRateSpinner.getValue(),//Hourly rate
                (long)addPhoneSpinner.getValue(),//Phone
                addAddressField.getText(),//address
                (int) addSportCenterSpinner.getValue(),//sportcentercode
                (int) addSportCodeSpinner.getValue()//sportcenter
        );
        if(newCoach.saveToDisk()){//If successfull
            JOptionPane.showMessageDialog(AdminFrame.this, "Coach Record added successfully");
        }
        else{
            JOptionPane.showMessageDialog(AdminFrame.this, "Couldn't save record...");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void studentIdRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIdRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIdRadioActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        if(coachIdRadio.isSelected()){
            Coach foundCoach = Coach.findInDisk((int) searchIdSpinner.getValue());
            if(foundCoach!=null){
                this.serachResultArea.setText(Coach.toJson(foundCoach));
            }
            else{
                JOptionPane.showMessageDialog(null, "Record not found...");
            }
        }
        else if(coachRatingsRadio.isSelected()){
            ArrayList<Coach> foundCoachList = Coach.findInDiskByRatings((int) searchIdSpinner.getValue());
            if(foundCoachList.size()>0){
                for(int j=0; j<foundCoachList.size(); j++){
                    this.serachResultArea.append(Coach.toJson(foundCoachList.get(j))+"\n");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Records not found...");
            }
        }
    }//GEN-LAST:event_searchButtonActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }
    private void populateCoachTable(DefaultTableModel coachTableModel){
        ArrayList<Coach> coachList = Coach.getAllCoaches();
        if(coachTableModel.getRowCount()>0){
            for(int i=0; i<coachTableModel.getRowCount(); i++){
                coachTableModel.removeRow(i);
            }
        }
        for(int i=0; i<coachList.size(); i++){
            Object[] row = new Object[10];
            row[0] = coachList.get(i).getId();
            row[1] = coachList.get(i).getName();
            row[2] = coachList.get(i).getDateJoined();
            row[3] = coachList.get(i).getDateTerminated();
            row[4] = coachList.get(i).getHourlyRate();
            row[5] = coachList.get(i).getPhone();
            row[6] = coachList.get(i).getAddress();
            row[7] = coachList.get(i).getSportCenterCode();
            row[8] = coachList.get(i).getSportCode();
            row[9] = coachList.get(i).getRatings();
            coachTableModel.addRow(row);
}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MODIFYPANEL;
    private javax.swing.JPanel SearchRecordPanel;
    private javax.swing.JPanel SortAndDisplayPanel;
    private javax.swing.JTextField addAddressField;
    private javax.swing.JSpinner addCoachIdSpinner;
    private javax.swing.JTextField addCoachNameField;
    private javax.swing.JSpinner addDateJoinedSpinner;
    private javax.swing.JSpinner addHourlyRateSpinner;
    private javax.swing.JSpinner addPhoneSpinner;
    private javax.swing.JPanel addRecordPanel;
    private javax.swing.JSpinner addSportCenterSpinner;
    private javax.swing.JSpinner addSportCodeSpinner;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton coachIdRadio;
    private javax.swing.JRadioButton coachRatingsRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JButton searchButton;
    private javax.swing.JSpinner searchIdSpinner;
    private javax.swing.JTextArea serachResultArea;
    private javax.swing.JRadioButton sportIdRadio;
    private javax.swing.JRadioButton studentIdRadio;
    // End of variables declaration//GEN-END:variables
}
