/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportAcademy;

import javax.swing.JOptionPane;

/**
 *
 * @author AsadUllah
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        adminButton = new javax.swing.JButton();
        userButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adminPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        adminUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        AdminLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        studentRegister = new javax.swing.JButton();
        userLogin = new javax.swing.JButton();
        stdIdSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminButton.setBackground(new java.awt.Color(204, 0, 204));
        adminButton.setText("ADMIN");
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        jPanel1.add(adminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 99, -1, -1));

        userButton.setBackground(new java.awt.Color(204, 0, 204));
        userButton.setText("Student");
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });
        jPanel1.add(userButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 214, 80, -1));

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USERNAME");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 109, -1, -1));

        adminPassword.setBackground(new java.awt.Color(0, 0, 204));
        adminPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(adminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 217, 154, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PASSWORD");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 225, -1, -1));

        adminUser.setBackground(new java.awt.Color(0, 0, 204));
        adminUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        adminUser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(adminUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 109, 154, 36));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ADMIN");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 29, -1, -1));

        AdminLogin.setBackground(new java.awt.Color(0, 0, 254));
        AdminLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        AdminLogin.setText("LOGIN");
        AdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLoginActionPerformed(evt);
            }
        });
        jPanel3.add(AdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 333, 113, 32));

        jLayeredPane1.add(jPanel3, "card2");

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 116, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        userPassword.setBackground(new java.awt.Color(0, 0, 204));
        userPassword.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(userPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 143, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Student");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 29, 290, -1));

        studentRegister.setBackground(new java.awt.Color(0, 0, 254));
        studentRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        studentRegister.setForeground(new java.awt.Color(255, 255, 255));
        studentRegister.setText("Register");
        studentRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(studentRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 113, 32));

        userLogin.setBackground(new java.awt.Color(0, 0, 254));
        userLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userLogin.setForeground(new java.awt.Color(255, 255, 255));
        userLogin.setText("LOGIN");
        userLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginActionPerformed(evt);
            }
        });
        jPanel2.add(userLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 113, 32));
        jPanel2.add(stdIdSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 140, 30));

        jLayeredPane1.add(jPanel2, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
       jLayeredPane1.removeAll();
       jLayeredPane1.add(jPanel3);
       jLayeredPane1.repaint();
       jLayeredPane1.revalidate();
    }//GEN-LAST:event_adminButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        jLayeredPane1.removeAll();
        jLayeredPane1.add(jPanel2);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }//GEN-LAST:event_userButtonActionPerformed

    private void studentRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRegisterActionPerformed
        (new RegisterStudent()).setVisible((true));
        LoginFrame.this.dispose();
    }//GEN-LAST:event_studentRegisterActionPerformed

    private void AdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLoginActionPerformed
        String name = adminUser.getText();
        char [] pass = adminPassword.getPassword();
        
        String password = new String(pass);
        
        if(name.equalsIgnoreCase("admin") && password.equalsIgnoreCase("admin")) JOptionPane.showMessageDialog(LoginFrame.this, "Login Successfull"); 
        else {JOptionPane.showMessageDialog(LoginFrame.this, "Please enter valid password or username"); return;};
        AdminFrame admin = new AdminFrame();
        admin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminLoginActionPerformed

    private void userLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginActionPerformed
        // TODO add your handling code here:
        Student found = Student.findInDisk((int)stdIdSpinner.getValue());
        if(found==null){
            JOptionPane.showMessageDialog(LoginFrame.this, "Sorry, record with given id doesn't exits");
        }
        else{
            if (!found.getPassword().equals(userPassword.getText())){
                JOptionPane.showMessageDialog(LoginFrame.this, "Please enter correct password");             
            }
            else{
                JOptionPane.showMessageDialog(LoginFrame.this, "Login Successfull");
               (new StudentFrame(found)).setVisible(true);
            }
        }
    }//GEN-LAST:event_userLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminLogin;
    private javax.swing.JButton adminButton;
    private javax.swing.JPasswordField adminPassword;
    private javax.swing.JTextField adminUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner stdIdSpinner;
    private javax.swing.JButton studentRegister;
    private javax.swing.JButton userButton;
    private javax.swing.JButton userLogin;
    private javax.swing.JPasswordField userPassword;
    // End of variables declaration//GEN-END:variables
}
