/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportAcademy;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Abdul Aziz
 */
public class RegisterStudent extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudent2
     */
    public RegisterStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new JLabel();
        nameLabel1 = new JLabel();
        regStudentName = new JTextField();
        nameLabel3 = new JLabel();
        regSportCenterCode = new JSpinner();
        foundCenterLabel = new JLabel();
        nameLabel2 = new JLabel();
        regSportCode = new JSpinner();
        foundSportLabel = new JLabel();
        nameLabel5 = new JLabel();
        regAge = new JSpinner();
        regStudentAddress = new JTextField();
        nameLabel6 = new JLabel();
        nameLabel = new JLabel();
        regPassword = new JPasswordField();
        jButton2 = new JButton();
        jButton1 = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new AbsoluteLayout());

        jLabel1.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setText("Student Registeration Portal");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new AbsoluteConstraints(10, 10, 590, 50));

        nameLabel1.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        nameLabel1.setText("Name:");
        nameLabel1.setName("nameLabel1"); // NOI18N
        getContentPane().add(nameLabel1, new AbsoluteConstraints(40, 80, 160, 30));

        regStudentName.setName("regStudentName"); // NOI18N
        getContentPane().add(regStudentName, new AbsoluteConstraints(230, 80, 310, 30));

        nameLabel3.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        nameLabel3.setText("Sport Center Code/ID:");
        nameLabel3.setName("nameLabel3"); // NOI18N
        getContentPane().add(nameLabel3, new AbsoluteConstraints(40, 120, 160, 30));

        regSportCenterCode.setModel(new SpinnerNumberModel());
        regSportCenterCode.setName("regSportCenterCode"); // NOI18N
        regSportCenterCode.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                regSportCenterCodeStateChanged(evt);
            }
        });
        getContentPane().add(regSportCenterCode, new AbsoluteConstraints(230, 120, 150, 30));

        foundCenterLabel.setText("No center found");
        foundCenterLabel.setName("foundCenterLabel"); // NOI18N
        getContentPane().add(foundCenterLabel, new AbsoluteConstraints(400, 130, 140, 20));

        nameLabel2.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        nameLabel2.setText("Sport Code/ID:");
        nameLabel2.setName("nameLabel2"); // NOI18N
        getContentPane().add(nameLabel2, new AbsoluteConstraints(40, 160, 160, 30));

        regSportCode.setModel(new SpinnerNumberModel());
        regSportCode.setName("regSportCode"); // NOI18N
        regSportCode.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                regSportCodeStateChanged(evt);
            }
        });
        getContentPane().add(regSportCode, new AbsoluteConstraints(230, 160, 150, 30));

        foundSportLabel.setText("No sport found");
        foundSportLabel.setName("foundSportLabel"); // NOI18N
        getContentPane().add(foundSportLabel, new AbsoluteConstraints(400, 170, 140, 20));

        nameLabel5.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        nameLabel5.setText("Age:");
        nameLabel5.setName("nameLabel5"); // NOI18N
        getContentPane().add(nameLabel5, new AbsoluteConstraints(40, 200, 160, 30));

        regAge.setModel(new SpinnerNumberModel());
        regAge.setName("regAge"); // NOI18N
        getContentPane().add(regAge, new AbsoluteConstraints(230, 200, 150, 30));

        regStudentAddress.setName("regStudentAddress"); // NOI18N
        regStudentAddress.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                regStudentAddressActionPerformed(evt);
            }
        });
        getContentPane().add(regStudentAddress, new AbsoluteConstraints(230, 240, 310, 30));

        nameLabel6.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        nameLabel6.setText("Address:");
        nameLabel6.setName("nameLabel6"); // NOI18N
        getContentPane().add(nameLabel6, new AbsoluteConstraints(40, 240, 160, 30));

        nameLabel.setFont(new Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Password");
        nameLabel.setName("nameLabel"); // NOI18N
        getContentPane().add(nameLabel, new AbsoluteConstraints(40, 280, 160, 30));

        regPassword.setName("regPassword"); // NOI18N
        getContentPane().add(regPassword, new AbsoluteConstraints(230, 280, 180, 30));

        jButton2.setText("Cancel");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new AbsoluteConstraints(40, 330, 90, 30));

        jButton1.setText("Register");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new AbsoluteConstraints(440, 330, 90, 30));

        pack();
    }//GEN-END:initComponents

    private void regSportCenterCodeStateChanged(ChangeEvent evt) {//GEN-FIRST:event_regSportCenterCodeStateChanged
        // TODO add your handling code here:
        SportCenter sp = SportCenter.findInDisk((int)regSportCenterCode.getValue());
        if(sp!=null){
            foundCenterLabel.setText(sp.getName());
        }
        else{
            foundCenterLabel.setText("No sport center found");
        }
    }//GEN-LAST:event_regSportCenterCodeStateChanged

    private void regSportCodeStateChanged(ChangeEvent evt) {//GEN-FIRST:event_regSportCodeStateChanged
        // TODO add your handling code here:
        Sport s = Sport.findInDisk((int)regSportCode.getValue());
        if(s!=null){
            foundSportLabel.setText(s.getName());
        }
        else{
            foundSportLabel.setText("No sport found");
        }
    }//GEN-LAST:event_regSportCodeStateChanged

    private void regStudentAddressActionPerformed(ActionEvent evt) {//GEN-FIRST:event_regStudentAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regStudentAddressActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        RegisterStudent.this.dispose();
        (new LoginFrame()).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(SportCenter.findInDisk((int)regSportCenterCode.getValue())==null){
            JOptionPane.showMessageDialog(RegisterStudent.this, "Sport Center record doesn't exit");
            return;
        }
        if(Sport.findInDisk((int)regSportCode.getValue())==null){
            JOptionPane.showMessageDialog(RegisterStudent.this, "Sport record doesn't exit");
            return ;
        }
        Student newStd = new Student(
                regStudentName.getText(),//name
                (int)regSportCenterCode.getValue(),//center code
                (int)regSportCode.getValue(),//sport code
                (int)regAge.getValue(),//age
                regStudentAddress.getText()//address
        );
        newStd.setPassword(regPassword.getText());
        if(newStd.saveToDisk()){
            JOptionPane.showMessageDialog(RegisterStudent.this, "Successfully Registered...\nYour ID(which will be used during login)s is: "+newStd.getId());
        }
        else{
            JOptionPane.showMessageDialog(RegisterStudent.this, "Couldn't save record...Please hit register button again...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel foundCenterLabel;
    private JLabel foundSportLabel;
    private JButton jButton1;
    private JButton jButton2;
    private JLabel jLabel1;
    private JLabel nameLabel;
    private JLabel nameLabel1;
    private JLabel nameLabel2;
    private JLabel nameLabel3;
    private JLabel nameLabel5;
    private JLabel nameLabel6;
    private JSpinner regAge;
    private JPasswordField regPassword;
    private JSpinner regSportCenterCode;
    private JSpinner regSportCode;
    private JTextField regStudentAddress;
    private JTextField regStudentName;
    // End of variables declaration//GEN-END:variables
}
